language: node_js
os: osx

node_js:
  - "8"

before_install:
  - cp src/renderer/config/index.example.js src/renderer/config/index.js
  - npm install yarn --global
  - yarn global add node-gyp

install:
  - yarn install

script: yarn run build:darwin
